# Generated by Django 4.1.13 on 2024-03-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DRI',
        ),
    ]
