# Generated by Django 5.0.1 on 2024-02-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meal_type',
            field=models.CharField(default='breakfast', max_length=50),
        ),
    ]
