# Generated by Django 5.0.1 on 2024-02-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0002_food_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.AddField(
            model_name='food',
            name='breakfast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='dinner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='lunch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='snacks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
