# Generated by Django 5.0.1 on 2024-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0003_mealdri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(max_length=100),
        ),
    ]
