# Generated by Django 5.0.1 on 2024-02-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0003_remove_food_meal_type_remove_food_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='food',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='food',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='food',
            name='snacks',
        ),
        migrations.AddField(
            model_name='food',
            name='food_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], default='Breakfast', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='Default Food Name', max_length=100),
        ),
    ]
